[build]
    functions="functions"

[functions]
  external_node_modules = ["express", "cors", "dotenv", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
    force=true
    to="/.netlify/functions/api/:splat"
    from="/*"
    status=200