[build]
    functions="functions"

[[redirects]]
    force=true
    to="/.netlify/functions/api/:splat"
    from="/*"
    status=200

[[headers]]
  for = "/api/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"